language: rust
sudo: false

env:
  global:
    - secure: IAFFw5r4IMQfI/cVeiPxmuFJidy5TI5Uh5xueLw5j5EtMC046LyRSQrsRwtzSzGdW8i3VfDLATgs7KOJsDbVl3ajKWy6Us9eHwq4kWyBqmgEUbLIj1t/M9IslSe0sJNiGznRcJXoJELm6t6KsZFVLTQIGaW/iAqVrO9jkpjUBvY=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
